version: '3.7'
services:

  web:
    build: .
    command: python run.py
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./services/web:/app
    environment:
      FLASK_APP: project/__init__.py
      FLASK_ENV: development

  db:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/db/login.sh:/login.sh
      - ./services/db/create_db.sql:/docker-entrypoint-initdb.d/1-create.sql
      - ./services/db/pop_db.sql:/docker-entrypoint-initdb.d/2-pop.sql
      - ./services/db/create_views.sql:/docker-entrypoint-initdb.d/3-view.sql
      - ./services/db/add_constraints.sql:/docker-entrypoint-initdb.d/4-constraints.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flight_radar_db

volumes:
  postgres_data: